package:
  name: fake_foldx
  version: "3.0.6"

build:
  noarch_python: True
  number: 2

requirements:
  run:
    - python
    - biopython

test:
  commands:
    - foldx -h

about:
  license: MIT
  summary: A dummy script that pretends that it's foldx when testing ELASPIC.

