image: condaforge/linux-anvil:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    # Build conda packages
    - conda config --append channels $CI_PROJECT_NAMESPACE
    - cd $CI_PROJECT_DIR/devtools/conda-recipe
    - conda build .
    # Save built packages as artifacts
    - mkdir $CI_PROJECT_DIR/conda-bld
    - cp -r /opt/conda/conda-bld/{linux-64,noarch} $CI_PROJECT_DIR/conda-bld
  artifacts:
    paths:
    - conda-bld

.test_template: &test_job
  stage: test
  before_script:
    - conda config --append channels $CI_PROJECT_NAMESPACE
    - cp -r $CI_PROJECT_DIR/conda-bld/* /opt/conda/conda-bld/
    - conda index /opt/conda/conda-bld/
    - conda install 'requests<2.12'
    - conda install -yq --use-local $CI_PROJECT_NAME

deploy:
  stage: deploy
  script:
    - anaconda -t $ANACONDA_TOKEN upload $CI_PROJECT_DIR/conda-bld/linux-64/*.tar.bz2 -u $CI_PROJECT_NAMESPACE -t test --force

deploy:
  stage: deploy
  script:
    - anaconda -t $ANACONDA_TOKEN upload $CI_PROJECT_DIR/conda-bld/linux-64/*.tar.bz2 -u $CI_PROJECT_NAMESPACE --force
  only:
    - master

# Tests

tools:
  <<: *test_job
  script:
    - py.test tests/test_tools
