sudo: false
language: python
python:
  - '3.4'
services:
  - mysql
install:
  # - wget https://repo.continuum.io/archive/Anaconda3-2.4.0-Linux-x86_64.sh -O anaconda.sh;
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O anaconda.sh;
  - bash anaconda.sh -b -p $HOME/anaconda
  - export PATH="$HOME/anaconda/bin:$PATH"
  - hash -r
  # Add relevant channels and install packages
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels bokeh
  - conda config --add channels ostrokach
  - conda config --add channels salilab
  - conda config --add channels r
  - conda config --add channels bioconda
  - conda info -a
  - conda update -q conda
  - conda install -q conda-build
  # Playing
  - conda install p7zip
  - which 7z
  - 7z --help || echo "Error!"
  - $HOME/anaconda/lib/p7zip/7z --help || echo "Error!"
  - bash -c "7z --help" || echo "Error!"
  - sed -i 's|#! /bin/sh|#!/bin/bash|' $(which 7z)
  - sed -i 's|#! /bin/sh|#!/bin/bash|' $(which 7za)
  - sed -i 's|#! /bin/sh|#!/bin/bash|' $(which 7zr)
  - 7z --help || echo "Error!"
  - bash -c "7z --help" || echo "Error!"
  # Build elaspic
  - conda build conda/elaspic
before_script:
  # Create a test environment
  - conda create -n _testing elaspic --use-local -y
  - source activate _testing
  - conda install -q -n _testing pytest pytest-cov
  - $TRAVIS_BUILD_DIR/scripts/configure_test.sh
script:
  - python -c "import elaspic"
  - ls /home/travis/anaconda/envs/_testing/lib
  - ls /home/travis/anaconda/envs/_testing/lib/p7zip
  - 7z --help
  - $TEST_DIR/scripts/run_test.sh
after_script:
  - python -c "import elaspic"
  - $TEST_DIR/scripts/cleanup_test.sh
after_success:
  - coveralls
env:
  global:
    - TEST_DIR="${HOME}/_test"
    - secure: XZ83x+3DutthNju8wiZVVfmQb/CW1HX0Zrymm4T1vNPjgm+ce6QzwY9NJfE/Mywh0/4EnZrg+WxJmJWMjV/RdZgm8GA9DMDtfVja8UDCo2OFrEv2LUL5GBO1d/3DJUZJB0rpmlTDyKkg8OQCZ/dOAKcxTKrdUVx/NDL78Kr2zMHj8CHXRg9ljjFG7tcui9JKur+Uvx70o70PKxFFOGfGKrkfmxp+MclkBTKlPPzoi7N0UmptO+wFfKnAQubiD2l4KqwilUrdRS2qFKlnzbay8r9FRqUS65KsmwJTaMdta+TYcDmOPWql6R7EjwIOZkrSLousTtz2AroL1FL1D8YmSUSC7JqJQHF/tC5kFXCEk7zgwJUht2FMBWPdIiM9qKZHGw+tw8tC5FxUzGCJe888DlgRQgcSc5BXbJfREsue3m6+yMBFwaFk+1URPhRSGqrgIl5gy5gswQwvq9Nojrtvy1xxCxxA+GGVj3QieVnTnrJeF3wFdfb/0IjGBEC4FmWPCSwtZWr+YUbfVzfvHav5I+01FN/0ckMnErZlYM9nta/H6r07yfPOBe6OMm/Fq2OzUoDas2WwvWO6FeUUxZKiCXj9hOH1Ofyr/sijjYyyZHykj5rJnTOWK3HbrpYZiqZiLweNn7Smo5QepkhSH4LJqAPO99c7UrWaj8ADVP9fcwYi=
  matrix:
    #- TEST_SUITE='local_1'
    - TEST_SUITE='database_1'
    #- TEST_SUITE='database_2'
