sudo: false
language: python
python:
  - '3.5'
services:
  - mysql
env:
  global:
    - PKG_NAME="elaspic"
    - SRC_DIR="${TRAVIS_BUILD_DIR}"
    - SCRIPTS_DIR="${TRAVIS_BUILD_DIR}/devtools/travis-ci"
    - TEST_DIR="${HOME}/_test"
  matrix:
    - TEST_SUITE='test_standalone_pipeline_1'
    - TEST_SUITE='test_database_pipeline_1'
    - TEST_SUITE='test_database_pipeline_2'
    - TEST_SUITE='test_unittests'
install:
  # Install Anaconda
  - wget --no-verbose -O anaconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh;
  - bash anaconda.sh -b -p $HOME/anaconda
  - export PATH="$HOME/anaconda/bin:$PATH"
  - hash -r
  # Add relevant channels
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels ostrokach
  - conda config --add channels https://conda.binstar.org/t/$ANACONDA_TOKEN/ostrokach
  - conda config --add channels kimlab
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda config --add channels salilab
  - conda config --add channels omnia
  - conda info -a
  # Install packages
  - conda update -q conda
  - conda install -q --yes conda-build
  # Build elaspic
  - conda build -q devtools/conda-recipe/
before_script:
  # Create a test environment
  - source activate _test
  - conda install -q --yes fake_provean fake_foldx anaconda-client
script:
  # Run tests
  - travis_wait 119 "${SCRIPTS_DIR}/travis-ci.sh"
after_success:
  - echo "Success!"
  - pip install codecov
  - codecov
  - |
    if [[ $TEST_SUITE == 'test_unittests' && \
          $TRAVIS_BRANCH = "master" && \
          $TRAVIS_PULL_REQUEST = false ]] ; then
        echo "Uploading to binstar..."
        conda install -q --yes anaconda-client
        anaconda -t ANACONDA_TOKEN upload /home/travis/anaconda/conda-bld/linux-64/*.tar.bz2
    fi
after_failure:
  - echo "Failure!"
after_script:
  - ${SCRIPTS_DIR}/cleanup_test.sh
  - echo "X_X"
