name: elaspic
channels:
- https://conda.anaconda.org/bioconda
- https://conda.anaconda.org/r
- https://conda.anaconda.org/ostrokach
dependencies:
- biopython=1.66=np110py35_0
- cython=0.23.4=py35_0
- docutils=0.12=py35_0
- elaspic=1.0.11=py35_1
- fastcache=1.0.2=py35_0
- foldx=3.0.6=5
- future=0.15.2=py35_0
- nose=1.3.7=py35_0
- numpy=1.10.2=py35_0
- p7zip=15.09=3
- pandas=0.17.1=np110py35_0
- path.py=8.1.2=py35_0
- pep8=1.6.2=py35_0
- pip=8.0.1=py35_0
- provean=1.1.5=1
- psutil=3.3.0=py35_0
- psycopg2=2.6.1=py35_0
- pytest=2.8.1=py35_0
- python=3.5.1=0
- python-dateutil=2.4.2=py35_0
- pyyaml=3.11=py35_1
- requests=2.9.0=py35_0
- retrying=1.3.3=py_1
- scikit-learn=0.17=np110py35_1
- scipy=0.16.1=np110py35_0
- six=1.10.0=py35_0
- sphinx=1.3.1=py35_0
- sphinx_rtd_theme=0.1.7=py35_0
- sqlalchemy=1.0.10=py35_0
- stride=1.6.4=1
- t_coffee=11.0.8=py35_1
