name: elaspic_test

channels:
- bioconda
- salilab
- defaults
- ostrokach

dependencies:
- alabaster=0.7.6=py35_0
- babel=2.1.1=py35_0
- biopython=1.66=np110py35_0
- blast=2.2.31=1
- boost=1.59.0=py35_4
- cd-hit=4.6.4=1
- curl=7.45.0=1
- docutils=0.12=py35_0
- elaspic=1.0.13=py35_1
- fastcache=1.0.2=py35_0
- foldx=3.0.6=5
- freetype=2.5.5=0
- funcsigs=0.4=py35_0
- future=0.15.2=py35_0
- hdf5-1813=1.8.13=0
- icu=55.1=0
- jbig=2.1=0
- jinja2=2.8=py35_0
- jpeg=8d=0
- knot=1.0.0=2
- libfaketime=0.9.6=1
- libgcc=4.8.5=1
- libgfortran=1.0=0
- libpng=1.6.17=0
- libtiff=4.0.6=1
- markupsafe=0.23=py35_0
- mock=1.0.1=py35_0
- modeller=9.15=py35_4
- msms=2.6.1=4
- mysql-connector-c=6.1.6=1
- mysqlclient=1.3.7=py35_1
- numpy=1.10.2=py35_0
- openblas=0.2.14=3
- openssl=1.0.2e=0
- p7zip=15.09=3
- pandas=0.17.1=np110py35_0
- pbr=1.3.0=py35_0
- pillow=3.0.0=py35_1
- pip=8.0.1=py35_0
- pops=1.6.4=1
- provean=1.1.5=1
- psutil=3.4.1=py35_0
- psycopg2=2.6.1=py35_0
- pygments=2.0.2=py35_0
- python=3.5.1=0
- python-dateutil=2.4.2=py35_0
- pytz=2015.7=py35_0
- pyyaml=3.11=py35_1
- readline=6.2=2
- requests=2.9.1=py35_0
- retrying=1.3.3=py_1
- scikit-learn=0.17=np110py35_1
- scipy=0.16.1=np110py35_0
- setuptools=19.4=py35_0
- six=1.10.0=py35_0
- snowballstemmer=1.2.0=py35_0
- sphinx=1.3.1=py35_0
- sphinx_rtd_theme=0.1.7=py35_0
- sqlalchemy=1.0.11=py35_0
- sqlite=3.9.2=0
- stride=1.6.4=1
- system=5.8=2
- t_coffee=11.0.8=py35_1
- tk=8.5.18=0
- wheel=0.26.0=py35_1
- xz=5.0.5=0
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - common==0.0.1
  - csvkit==0.9.2
  - s4cmd==1.5.23
  - sphinx-rtd-theme==0.1.7
  - synapseclient==1.4
  - wiki==0.1.dev0
