name: elaspic
channels:
- https://conda.anaconda.org/bioconda
- https://conda.anaconda.org/r
- https://conda.anaconda.org/ostrokach
dependencies:
- python=3.5.1=0
- elaspic=1.0.11=py35_1
- sphinx=1.3.1=py35_0
- sphinx_rtd_theme=0.1.7=py35_0
