name: elaspic
dependencies:
- biopython=1.65=np19py34_0
- cython=0.22=py34_0
- dateutil=2.4.1=py34_0
- docutils=0.12=py34_0
- fastcache=1.0.2=py34_0
- future=0.14.3=py34_0
- jinja2=2.7.3=py34_1
- markupsafe=0.23=py34_0
- nose=1.3.4=py34_1
- numpy=1.9.2=py34_0
- openssl=1.0.1k=1
- pandas=0.15.2=np19py34_1
- pip=6.0.8=py34_0
- psutil=2.2.1=py34_0
- psycopg2=2.6=py34_0
- py=1.4.26=py34_0
- pygments=2.0.2=py34_0
- pytest=2.6.4=py34_0
- python=3.4.3=0
- python-dateutil=2.4.1=py34_0
- pytz=2014.9=py34_0
- readline=6.2=2
- scikit-learn=0.15.2=np19py34_0
- scipy=0.15.1=np19py34_0
- setuptools=14.3=py34_0
- six=1.9.0=py34_0
- sqlalchemy=0.9.9=py34_0
- sqlite=3.8.4.1=1
- system=5.8=1
- tk=8.5.18=0
- xz=5.0.5=0
- zlib=1.2.8=0
- pip:
  - mysqlclient==1.3.6
  - sphinx>=1.3
  - sphinxcontrib-programoutput>=0.8
  - retrying>=1.3.3
