package:
  name: foldx
  version: "3.0.6.mock"

build:
  noarch_python: True
  number: 0

requirements:
  run:
    - python
    - biopython

test:
  commands:
    - foldx -h

about:
  license: MIT
  summary: A dummy script that pretends that it's foldx when testing ELASPIC.
