#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Created on Thu Nov  5 17:09:54 2015

@author: strokach
"""
import os.path as op
import argparse


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-q', '--sequence_file', required=True)
    parser.add_argument('-v', '--mutation_file', required=True)
    parser.add_argument('-d', '--blast_db_dir', required=True)
    parser.add_argument('--tmp_dir', required=True, help="provean_temp_dir")
    parser.add_argument('--num_threads', required=True)
    parser.add_argument('--psiblast', required=True)
    parser.add_argument('--blastdbcmd', required=True)
    parser.add_argument('--cdhit', required=True)
    parser.add_argument('--supporting_set', default='')
    parser.add_argument('--save_supporting_set', default='')

    args = parser.parse_args()
    assert op.isfile(args.sequence_file)
    assert op.isfile(args.mutation_file)
    assert op.isdir(args.blast_db_dir)
    assert op.isdir(args.tmp_dir)
    assert op.isfile(args.psiblast)
    assert op.isfile(args.blastdbcmd)
    assert op.isfile(args.cdhit)
    assert op.isfile(args.supporting_set) or args.save_supporting_set

    return args


def main():
    args = parse_args()
    with open(args.mutation_file) as ifh:
        mutation = ifh.read.strip()
    print('# VARIATION            SCORE')
    print('{} {}'.format(mutation, 0))
    if args.save_supporting_set:
        with open(args.save_supporting_set) as ofh:
            ofh.write('fake_provean supporting set')
        with open(args.save_supporting_set + '.fasta') as ofh:
            ofh.write('fake_provean supporting set fasta file')

if __name__ == '__main__':
    main()
