package:
  name: elaspic
  version: "1.0.2"

source:
  path: ../..

build:
  number: 1
  entry_points: 
    - elaspic = elaspic.__main__:elaspic
    - elaspic_database = elaspic.__main__:elaspic_database

requirements:
  build:
    # Basic python
    - python
    - retrying
    - pyyaml
    # Scientific python
    - fastcache
    - numpy
    - scipy
    - pandas
    - psutil
    - scikit-learn
    - biopython
    # Python 2 / 3 compatibility
    - future
    - six
    # Database access
    - sqlalchemy
    - sqlite
    - mysqlclient
    - psycopg2
    # Binary files
    - stride
    - knot
    - pops
    - msms
    - t_coffee
    - modeller ==9.15
    - cd-hit
    - fake_provean  # in order to speed up tests
    - foldx
    - libfaketime
  run:
    # Basic python
    - python
    - pyyaml
    - psutil
    - retrying
    - fastcache
    # Scientific python
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - biopython
    # Python 2 / 3 compatibility
    - future
    - six
    # Database access
    - sqlalchemy
    - sqlite
    - mysqlclient
    - psycopg2
    # Binary files
    - stride
    - knot
    - pops
    - msms
    - t_coffee
    - modeller ==9.15
    - cd-hit
    - fake_provean  # in order to speed up tests
    - foldx
    - libfaketime

test:
  imports:
    - elaspic
  commands:
    - elaspic --help
    - elaspic_database --help
      
about:
  home: elaspic.kimlab.org
  license: MIT
  summary: Ensemble Learning Approach for Stability Prediction of 
           Interface and Core mutations (ELASPIC).
