package:
  name: elaspic
  version: "1.0.0"

source:
  path: ../..

build:
  number: 1
  entry_points: 
    - elaspic = elaspic.__main__:elaspic
    - elaspic_database = elaspic.__main__:elaspic_database

requirements:
  build:
    - python
    - setuptools
    #~ - binstar-build
  run:
    # System
    - ncurses

    # Basic python
    - python
    - dateutil
    - python-dateutil
    - pytz
    - retrying
    
    # Scientific python
    - fastcache
    - numpy
    - scipy
    - pandas ==0.15.2
    - psutil
    - scikit-learn ==0.15.2
    - cython
    - biopython

    # Testing
    - pytest
    - nose

    # Documentation
    - docutils
    - sphinx >=1.3
    - sphinxcontrib-programoutput
    - jinja2
    - markupsafe

    # Python 2 / 3 compatibility
    - future
    - six

    # Database access
    - sqlalchemy
    - sqlite
    - mysqlclient
    - psycopg2

    # Binary files
    - stride
    - knot
    - pops
    - msms
    - t_coffee
    - modeller
    - cd-hit
    - provean
    - foldx
    - libfaketime

# Can't get this to work without `elaspic` already being on anaconda.org.
test:
  requires:
    - pytest
  imports:
    - elaspic
  commands:
    - elaspic --help
    - elaspic_database --help

about:
  home: elaspic.kimlab.org
  license: MIT
  summary: Ensemble Learning Approach for Stability Prediction of 
           Interface and Core mutations (ELASPIC).
