package:
  name: elaspic
  version: "1.0.0"

source:
  path: ../..

build:
  number: 1
  entry_points: 
    - elaspic = elaspic.__main__:elaspic
    - elaspic_database = elaspic.__main__:elaspic_database

requirements:
  build:
    - python
    - numpy
    - pandas
    - scikit-learn
  run:
    # Basic python
    - python
    - retrying
    # Scientific python
    - fastcache
    - numpy
    - scipy
    - pandas
    - psutil
    - scikit-learn
    - biopython
    # Testing
    - pytest
    # Documentation
    - sphinx >=1.3
    - sphinxcontrib-programoutput
    - jinja2
    - markupsafe
    # Python 2 / 3 compatibility
    - future
    - six
    # Database access
    - sqlalchemy
    - sqlite
    - mysqlclient
    - psycopg2
    # Binary files
    - stride
    - knot
    - pops
    - msms
    - t_coffee
    - modeller
    - cd-hit
    - provean
    - foldx
    - libfaketime

test:
  requires:
    - pytest
  imports:
    - elaspic
  commands:
    - elaspic --help
    - elaspic_database --help

about:
  home: elaspic.kimlab.org
  license: MIT
  summary: Ensemble Learning Approach for Stability Prediction of 
           Interface and Core mutations (ELASPIC).
