package:
  name: elaspic
  version: 0.1.40.dev0

source:
  path: ../../

build:
  number: 1
  entry_points:
    - elaspic = elaspic.__main__:main

requirements:
  build:
    - perl  # for modeller installation
    # Basic python
    - python
    - pyyaml
    - requests
    - psutil
    - retrying
    # Scientific python
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - biopython
    - libfaketime
    - modeller >=9.16
    # Database access
    - sqlalchemy
    # - mysqlclient  # can use PyMYSQL instead...
    # Kimlab
    - kmtools ==0.0.13
    - icu  # required by lxml in kmtools < 0.0.18
  run:
    # Basic python
    - python
    - pyyaml
    - requests
    - psutil
    - retrying
    # Scientific python
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - biopython
    - libfaketime
    - modeller >=9.16
    # Database access
    - sqlalchemy
    # - mysqlclient  # can use PyMYSQL instead...
    # Kimlab
    - kmtools ==0.0.13
    - icu  # required by lxml in kmtools < 0.0.18
    # Binary files
    - p7zip
    - blast
    - stride
    - pops
    - msms
    - t_coffee
    - cd-hit
    - provean  # can't install fake_provean for tests if this is installed...
    - foldx  # private only and breaks readthedocs

test:
  requires:
    - pytest
    - pytest-runner
    - pytest-cov
    - pep8
    - flake8
    - provean ==1.0.3.mock
    - foldx ==3.0.6.mock
  imports:
    - elaspic
  commands:
    - elaspic --help
    - elaspic run --help
    - elaspic database --help

about:
  home: http://elaspic.kimlab.org
  license: MIT
  summary: Ensemble Learning Approach for Stability Prediction of
           Interface and Core mutations (ELASPIC).
