package:
  name: elaspic
  version: 0.2.0

source:
  path: ../../

build:
  number: 0
  entry_points:
    - elaspic = elaspic.__main__:main

requirements:
  build:
    # Basic python
    - python
    - pyyaml
    - requests
    - psutil
    # Scientific python
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - modeller
    # Kimlab
    - kmbio
    - kmtools
  run:
    # Basic python
    - python
    - pyyaml
    - requests
    - psutil
    # Scientific python
    - numpy
    - scipy
    - pandas
    - scikit-learn
    # Database access
    - mysql
    - mysqlclient
    - sqlalchemy
    # Kimlab
    - kmbio
    - kmtools
    # Binary files
    - modeller
    - p7zip
    - blast
    - stride ==1.6.4
    - pops
    - msms
    - t_coffee
    - cd-hit
    - provean
    - foldx
    - libfaketime

test:
  imports:
    - elaspic
  commands:
    - elaspic --help
    - elaspic run --help
    - elaspic database --help

about:
  home: http://elaspic.kimlab.org
  license: MIT
  summary: "Ensemble Learning Approach for Stability Prediction of
           Interface and Core mutations (ELASPIC)."
