 {% set version = "0.1.40" %}

package:
  name: elaspic
  version: {{ version }}

source:
  path: ../../

build:
  number: 0
  entry_points:
    - elaspic = elaspic.__main__:main

requirements:
  build:
    # Basic python
    - python
    - pyyaml
    - requests
    - psutil
    - retrying
    # Scientific python
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - biopython
    - libfaketime
    - modeller
    # Database access
    - sqlalchemy
    - mysqlclient
    # Kimlab
    - kmtools
  run:
    # Basic python
    - python
    - pyyaml
    - requests
    - psutil
    - retrying
    # Scientific python
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - biopython
    - libfaketime
    - modeller
    # Database access
    - sqlalchemy
    - mysqlclient
    # Kimlab
    - kmtools
    # Binary files
    - p7zip
    - blast
    - stride ==1.6.4
    - pops
    - msms
    - t_coffee
    - cd-hit
    - provean
    - foldx

test:
  imports:
    - elaspic
  commands:
    - elaspic --help
    - elaspic run --help
    - elaspic database --help

about:
  home: http://elaspic.kimlab.org
  license: MIT
  summary: "Ensemble Learning Approach for Stability Prediction of
           Interface and Core mutations (ELASPIC)."
