package:
  name: elaspic
  version: 1.0.22

source:
  path: ../../

build:
  number: 0
  entry_points:
    - elaspic = elaspic.__main__:main

requirements:
  build:
    # Basic python
    - python
    - pyyaml
    - requests
    # Scientific python
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - biopython
  run:
    # Basic python
    - python
    - pyyaml
    - requests
    - psutil
    - retrying
    - fastcache
    # Scientific python
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - biopython
    # Database access
    - sqlalchemy
    - sqlite
    - mysqlclient
    - psycopg2
    # Binary files
    - p7zip
    - blast
    - stride
    - knot
    - pops
    - msms
    - t_coffee
    - modeller
    - cd-hit
    # - provean  # can't install fake_provean for tests if this is installed...
    # - foldx  # private only and breaks readthedocs
    - libfaketime

test:
  requires:
    - pytest
    - pytest-runner
    - pytest-cov
    - pep8
    - flake8
    - fake_provean
    - fake_foldx
  imports:
    - elaspic
  commands:
    - elaspic --help
    - elaspic database --help

about:
  home: elaspic.kimlab.org
  license: MIT
  summary: Ensemble Learning Approach for Stability Prediction of
           Interface and Core mutations (ELASPIC).
