package:
  name: provean
  version: "1.0.3.mock"

build:
  noarch_python: True
  number: 0

requirements:
  run:
    - python

test:
  commands:
    - provean -h

about:
  license: MIT
  summary: A dummy script that pretends that it's provean when testing ELASPIC.
